/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes.java;

import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;


public class App {

    public static void main(String[] args) throws FileNotFoundException {

        getRandomQuote();
    }


    public static void getRandomQuote() {

        try {
            // make a request to the number facts API
            URL url = new URL("https://ron-swanson-quotes.herokuapp.com/v2/quotes");
            HttpURLConnection con = (HttpURLConnection) url.openConnection();

            // this line of code actually goes to the internet!
            BufferedReader reader = new BufferedReader(new InputStreamReader((con.getInputStream())));

            // get json data in response
            // use GSON to parse json string into a number fact object
            Gson gson = new Gson();
            RonSwansonQuote[] rsQuote = gson.fromJson(reader, RonSwansonQuote[].class);
            // access the text of the number fact
            // return that text so that it can be printed

        } catch (IOException e) {
            System.out.println(e);
        }



    }
}
